Feat/dob 50 refactor consulting type loading
virtualidentityag/diakonie-onlineBeratung-agencyService pull request #5
Opened 2021-05-10 08:52 UTC by Schweizer-Philipp

2021-05-11 15:35 UTC, PepeCortisona approved these changes

2021-05-12 07:42 UTC, daho4b requested changes
See comments

2021-05-12 07:42 UTC, daho4b commented on services/consultingtypeservice.yaml
> +  title: will be replaced
the file has been updated in the service, please update the file here as well

2021-05-12 07:42 UTC, daho4b commented on src/main/resources/application.properties
> +cache.consulting.type.configuration.timeToLiveSeconds=10800
I would suggest increasing the value for 'timeToLiveSeconds'

2021-05-12 07:42 UTC, daho4b commented on src/test/java/de/caritas/cob/agencyservice/testHelper/ExtendedConsultingTypeResponseDTOHelper.java
> +    if (whiteSpot != null) {
Please replace != null with nonNull(...)

2021-05-17 07:16 UTC, PepeCortisona approved these changes

2021-05-17 07:28 UTC, merged